### ISSUE TITLE
本地run dev报错

### ISSUE THREAD

**Issue by arlendp** [pluto1114/vue-music163#1]
本地运行`node run dev`报错
![image](https://cloud.githubusercontent.com/assets/9403654/21853648/eb7a491a-d852-11e6-9777-1d8dfedb02ab.png)

**Comment by pluto1114** [comment]
建议在git pull一下，然后重新执行npm install，我刚才完整测试过了，应该没有问题

**Comment by arlendp** [comment]
@pluto1114 ，不好意思，我这边是占用了`8080`端口导致的问题，现在可以运行了，非常感谢。`package.json`中好像有地方误写了吧，`lodash`写成了`ladash`。

**Comment by pluto1114** [comment]
lodash那里确实拼写错了，已改正，谢谢反馈
